export enum ActionType{
    MAKE_REQ="MAKE_REQ",
    REQ_GETALL_SUCC="REQ_GETALL_SUCC",
    REQ_GETALL_FAIL="REQ_GETALL_FAIL",
    OPEN_POPUP="OPEN_POPUP",
    REQ_ADD_SUCC="REQ_ADD_SUCC",
    REQ_UPDATE_SUCC="REQ_UPDATE_SUCC",
    REQ_DELETE_SUCC="REQ_DELETE_SUCC",
    REQ_GETBYCODE_SUCC="REQ_GETBYCODE_SUCC"
}
